export const siteConfig = {
  name: 'Dr. Suryakanta Parida',
  title: 'Best Gastroenterologist in Cuttack & Bhubaneswar | Dr. Suryakanta Parida',
  description:
    'Expert gastroenterology care by Dr. Suryakanta Parida – MBBS, MD, DM Gastroenterologist. Endoscopy, Colonoscopy, Liver Disease & GI Disorders at Sai Shree Polyclinic, Cuttack. Serving patients from Bhubaneswar & Odisha.',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://drsuryakantaparida.com',
  phone: '+91 7008512773',
  phoneRaw: '+917008512773',
  clinic: 'Sai Shree Polyclinic',
  hospital: 'S.C.B Medical College, Cuttack',
  location: 'Cuttack & Bhubaneswar, Odisha',
  designation: 'Associate Professor',
  department: 'Department of Gastroenterology',
  qualifications: 'MBBS, MD (Medicine), DM (Gastroenterology)',
  keywords: [
    'Gastroenterologist in Cuttack',
    'Gastroenterologist in Bhubaneswar',
    'Best Gastro Doctor Odisha',
    'Best gastro doctor Bhubaneswar',
    'Endoscopy Specialist Cuttack',
    'Endoscopy in Cuttack',
    'Endoscopy test Bhubaneswar',
    'Colonoscopy Cuttack',
    'Colonoscopy in Bhubaneswar',
    'Colon cancer screening Odisha',
    'Liver Doctor Odisha',
    'Liver specialist Odisha',
    'Fatty liver treatment Cuttack',
    'Hepatitis specialist Bhubaneswar',
    'GI doctor near me',
    'Stomach doctor Cuttack',
    'GERD specialist Odisha',
    'DM Gastroenterology Cuttack',
    'SCB Medical College Gastroenterology',
    'Sai Shree Polyclinic',
    'Digestive Disorder Specialist Odisha',
  ],
  ogImage: '/images/og-image.jpg',
  twitterHandle: '@drsuryakantaparida',
};
